//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ArticleNumber
    {
        public decimal Arti_ID { get; set; }
        public string Arti_No { get; set; }
        public string Arti_Des { get; set; }
    }
}
