//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DB_Connection
    {
        public decimal ConID { get; set; }
        public string ConString { get; set; }
        public string TableName { get; set; }
        public string SrNoColumnName { get; set; }
        public string ArtiColumnName { get; set; }
        public string DateColumnName { get; set; }
        public string StartTimeColName { get; set; }
        public string EndTimeColName { get; set; }
        public string StatusColumnName { get; set; }
        public string OperColumnName { get; set; }
        public string RptLocColumnName { get; set; }
        public string SystemName { get; set; }
        public string Fields { get; set; }
    }
}
