//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Item
    {
        public decimal ItemID { get; set; }
        public string ItemName { get; set; }
        public string Type { get; set; }
        public string TestStation { get; set; }
        public string ArticleNumber { get; set; }
        public string ValidateTest { get; set; }
    }
}
