//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class URVEntities1 : DbContext
    {
        public URVEntities1()
            : base("name=URVEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_ArticleNumber> TB_ArticleNumber { get; set; }
        public virtual DbSet<TB_DB_Connection> TB_DB_Connection { get; set; }
        public virtual DbSet<TB_Item> TB_Item { get; set; }
        public virtual DbSet<TB_TestStage> TB_TestStage { get; set; }
        public virtual DbSet<TB_ITrAR> TB_ITrAR { get; set; }
        public virtual DbSet<TB_ITrDB> TB_ITrDB { get; set; }
        public virtual DbSet<TB_ITrTS> TB_ITrTS { get; set; }
        public virtual DbSet<TB_TSrAR> TB_TSrAR { get; set; }
    }
}
